# Generated by Django 4.2.9 on 2025-12-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_remove_user_telegram_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
