# Generated by Django 4.2.9 on 2025-12-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_options_remove_user_telegram_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="telegram_chat_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Уникальный email пользователя",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
