# Generated by Django 4.2.27 on 2025-12-17 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "Ежедневно"), ("weekly", "Еженедельно")],
                        default="daily",
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                ("execution_time", models.TimeField(verbose_name="Время выполнения")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Максимальное время выполнения в секундах",
                        verbose_name="Длительность (секунды)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичная"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем себя наградить за выполнение",
                        max_length=255,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, связанная с полезной",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                check=models.Q(("duration__lte", 120)), name="duration_max_120_seconds"
            ),
        ),
    ]
