# Generated by Django 4.2.27 on 2025-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.TimeField(
                blank=True,
                help_text="Время выполнения привычки (необязательно)",
                null=True,
                verbose_name="Время выполнения",
            ),
        ),
    ]
