# Generated by Django 4.2.27 on 2025-12-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_alter_habit_execution_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время выполнения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habits.habit",
                        verbose_name="Привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
                "ordering": ["-completed_at"],
            },
        ),
    ]
