# Generated by Django 4.2.9 on 2025-12-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0003_habitcompletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="action",
            field=models.CharField(
                blank=True,
                help_text="Действие, которое представляет собой привычка",
                max_length=500,
                verbose_name="Действие",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Является ли привычка приятной (вознаграждением)",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True,
                help_text="Место, в котором необходимо выполнять привычку",
                max_length=255,
                verbose_name="Место",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Время, когда необходимо выполнять привычку",
                null=True,
                verbose_name="Время",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
        ),
    ]
